scrape_configs:
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        # Frontend
        - https://techforing.com
        - https://hrms.techforing.com
        - https://cms.techforing.com
        - https://customer.techforing.com
        - https://growth.techforing.com
        # Backend
        - https://careeradmin.techforing.com/admin/
        - https://cmsadmin.techforing.com/admin/
        - https://customeradmin.techforing.com/admin/
        # Dev
        # Frontend
        - https://main.techforing.com/
        - https://devcms.techforing.com/
        - https://devcareer.techforing.com/
        - https://devgrowth.techforing.com/
        # Backend
        - https://devcmsadmin.techforing.com/admin/
        - https://devhrms.techforing.com/
        - https://devcareeradmin.techforing.com/
        - https://react.techforing.com/
        - https://admin.techforing.com/
        - https://devtenant.techforing.com/login
        - https://devapitenant.techforing.com/login
        - https://devapiauth.techforing.com/admin/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115